/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef client_master_CONSTANTS_H
#define client_master_CONSTANTS_H

#include "client_master_types.h"



class client_masterConstants {
 public:
  client_masterConstants();

};

extern const client_masterConstants g_client_master_constants;



#endif
