/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "client_master_constants.h"



const client_masterConstants g_client_master_constants;

client_masterConstants::client_masterConstants() {
}



