/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MasterRPCService_H
#define MasterRPCService_H

#include <thrift/TDispatchProcessor.h>
#include "client_master_types.h"



class MasterRPCServiceIf {
 public:
  virtual ~MasterRPCServiceIf() {}
  virtual void RequestWorker(WorkerMeta& _return, const int32_t client_pid) = 0;
  virtual void GetCurrentClientStates(std::vector<MasterClientMetaState> & _return) = 0;
};

class MasterRPCServiceIfFactory {
 public:
  typedef MasterRPCServiceIf Handler;

  virtual ~MasterRPCServiceIfFactory() {}

  virtual MasterRPCServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MasterRPCServiceIf* /* handler */) = 0;
};

class MasterRPCServiceIfSingletonFactory : virtual public MasterRPCServiceIfFactory {
 public:
  MasterRPCServiceIfSingletonFactory(const boost::shared_ptr<MasterRPCServiceIf>& iface) : iface_(iface) {}
  virtual ~MasterRPCServiceIfSingletonFactory() {}

  virtual MasterRPCServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MasterRPCServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<MasterRPCServiceIf> iface_;
};

class MasterRPCServiceNull : virtual public MasterRPCServiceIf {
 public:
  virtual ~MasterRPCServiceNull() {}
  void RequestWorker(WorkerMeta& /* _return */, const int32_t /* client_pid */) {
    return;
  }
  void GetCurrentClientStates(std::vector<MasterClientMetaState> & /* _return */) {
    return;
  }
};

typedef struct _MasterRPCService_RequestWorker_args__isset {
  _MasterRPCService_RequestWorker_args__isset() : client_pid(false) {}
  bool client_pid :1;
} _MasterRPCService_RequestWorker_args__isset;

class MasterRPCService_RequestWorker_args {
 public:

  static const char* ascii_fingerprint; // = "E86CACEB22240450EDCBEFC3A83970E4";
  static const uint8_t binary_fingerprint[16]; // = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};

  MasterRPCService_RequestWorker_args(const MasterRPCService_RequestWorker_args&);
  MasterRPCService_RequestWorker_args& operator=(const MasterRPCService_RequestWorker_args&);
  MasterRPCService_RequestWorker_args() : client_pid(0) {
  }

  virtual ~MasterRPCService_RequestWorker_args() throw();
  int32_t client_pid;

  _MasterRPCService_RequestWorker_args__isset __isset;

  void __set_client_pid(const int32_t val);

  bool operator == (const MasterRPCService_RequestWorker_args & rhs) const
  {
    if (!(client_pid == rhs.client_pid))
      return false;
    return true;
  }
  bool operator != (const MasterRPCService_RequestWorker_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterRPCService_RequestWorker_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const MasterRPCService_RequestWorker_args& obj);
};


class MasterRPCService_RequestWorker_pargs {
 public:

  static const char* ascii_fingerprint; // = "E86CACEB22240450EDCBEFC3A83970E4";
  static const uint8_t binary_fingerprint[16]; // = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};


  virtual ~MasterRPCService_RequestWorker_pargs() throw();
  const int32_t* client_pid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const MasterRPCService_RequestWorker_pargs& obj);
};

typedef struct _MasterRPCService_RequestWorker_result__isset {
  _MasterRPCService_RequestWorker_result__isset() : success(false) {}
  bool success :1;
} _MasterRPCService_RequestWorker_result__isset;

class MasterRPCService_RequestWorker_result {
 public:

  static const char* ascii_fingerprint; // = "8FDCDECDA8B6AD05EDA17B7792CE4D80";
  static const uint8_t binary_fingerprint[16]; // = {0x8F,0xDC,0xDE,0xCD,0xA8,0xB6,0xAD,0x05,0xED,0xA1,0x7B,0x77,0x92,0xCE,0x4D,0x80};

  MasterRPCService_RequestWorker_result(const MasterRPCService_RequestWorker_result&);
  MasterRPCService_RequestWorker_result& operator=(const MasterRPCService_RequestWorker_result&);
  MasterRPCService_RequestWorker_result() {
  }

  virtual ~MasterRPCService_RequestWorker_result() throw();
  WorkerMeta success;

  _MasterRPCService_RequestWorker_result__isset __isset;

  void __set_success(const WorkerMeta& val);

  bool operator == (const MasterRPCService_RequestWorker_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MasterRPCService_RequestWorker_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterRPCService_RequestWorker_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const MasterRPCService_RequestWorker_result& obj);
};

typedef struct _MasterRPCService_RequestWorker_presult__isset {
  _MasterRPCService_RequestWorker_presult__isset() : success(false) {}
  bool success :1;
} _MasterRPCService_RequestWorker_presult__isset;

class MasterRPCService_RequestWorker_presult {
 public:

  static const char* ascii_fingerprint; // = "8FDCDECDA8B6AD05EDA17B7792CE4D80";
  static const uint8_t binary_fingerprint[16]; // = {0x8F,0xDC,0xDE,0xCD,0xA8,0xB6,0xAD,0x05,0xED,0xA1,0x7B,0x77,0x92,0xCE,0x4D,0x80};


  virtual ~MasterRPCService_RequestWorker_presult() throw();
  WorkerMeta* success;

  _MasterRPCService_RequestWorker_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const MasterRPCService_RequestWorker_presult& obj);
};


class MasterRPCService_GetCurrentClientStates_args {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  MasterRPCService_GetCurrentClientStates_args(const MasterRPCService_GetCurrentClientStates_args&);
  MasterRPCService_GetCurrentClientStates_args& operator=(const MasterRPCService_GetCurrentClientStates_args&);
  MasterRPCService_GetCurrentClientStates_args() {
  }

  virtual ~MasterRPCService_GetCurrentClientStates_args() throw();

  bool operator == (const MasterRPCService_GetCurrentClientStates_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MasterRPCService_GetCurrentClientStates_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterRPCService_GetCurrentClientStates_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const MasterRPCService_GetCurrentClientStates_args& obj);
};


class MasterRPCService_GetCurrentClientStates_pargs {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~MasterRPCService_GetCurrentClientStates_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const MasterRPCService_GetCurrentClientStates_pargs& obj);
};

typedef struct _MasterRPCService_GetCurrentClientStates_result__isset {
  _MasterRPCService_GetCurrentClientStates_result__isset() : success(false) {}
  bool success :1;
} _MasterRPCService_GetCurrentClientStates_result__isset;

class MasterRPCService_GetCurrentClientStates_result {
 public:

  static const char* ascii_fingerprint; // = "D6228998CE1A24A087C8DF0ED2349F0F";
  static const uint8_t binary_fingerprint[16]; // = {0xD6,0x22,0x89,0x98,0xCE,0x1A,0x24,0xA0,0x87,0xC8,0xDF,0x0E,0xD2,0x34,0x9F,0x0F};

  MasterRPCService_GetCurrentClientStates_result(const MasterRPCService_GetCurrentClientStates_result&);
  MasterRPCService_GetCurrentClientStates_result& operator=(const MasterRPCService_GetCurrentClientStates_result&);
  MasterRPCService_GetCurrentClientStates_result() {
  }

  virtual ~MasterRPCService_GetCurrentClientStates_result() throw();
  std::vector<MasterClientMetaState>  success;

  _MasterRPCService_GetCurrentClientStates_result__isset __isset;

  void __set_success(const std::vector<MasterClientMetaState> & val);

  bool operator == (const MasterRPCService_GetCurrentClientStates_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MasterRPCService_GetCurrentClientStates_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterRPCService_GetCurrentClientStates_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const MasterRPCService_GetCurrentClientStates_result& obj);
};

typedef struct _MasterRPCService_GetCurrentClientStates_presult__isset {
  _MasterRPCService_GetCurrentClientStates_presult__isset() : success(false) {}
  bool success :1;
} _MasterRPCService_GetCurrentClientStates_presult__isset;

class MasterRPCService_GetCurrentClientStates_presult {
 public:

  static const char* ascii_fingerprint; // = "D6228998CE1A24A087C8DF0ED2349F0F";
  static const uint8_t binary_fingerprint[16]; // = {0xD6,0x22,0x89,0x98,0xCE,0x1A,0x24,0xA0,0x87,0xC8,0xDF,0x0E,0xD2,0x34,0x9F,0x0F};


  virtual ~MasterRPCService_GetCurrentClientStates_presult() throw();
  std::vector<MasterClientMetaState> * success;

  _MasterRPCService_GetCurrentClientStates_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const MasterRPCService_GetCurrentClientStates_presult& obj);
};

class MasterRPCServiceClient : virtual public MasterRPCServiceIf {
 public:
  MasterRPCServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MasterRPCServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void RequestWorker(WorkerMeta& _return, const int32_t client_pid);
  void send_RequestWorker(const int32_t client_pid);
  void recv_RequestWorker(WorkerMeta& _return);
  void GetCurrentClientStates(std::vector<MasterClientMetaState> & _return);
  void send_GetCurrentClientStates();
  void recv_GetCurrentClientStates(std::vector<MasterClientMetaState> & _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MasterRPCServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MasterRPCServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MasterRPCServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_RequestWorker(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetCurrentClientStates(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MasterRPCServiceProcessor(boost::shared_ptr<MasterRPCServiceIf> iface) :
    iface_(iface) {
    processMap_["RequestWorker"] = &MasterRPCServiceProcessor::process_RequestWorker;
    processMap_["GetCurrentClientStates"] = &MasterRPCServiceProcessor::process_GetCurrentClientStates;
  }

  virtual ~MasterRPCServiceProcessor() {}
};

class MasterRPCServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MasterRPCServiceProcessorFactory(const ::boost::shared_ptr< MasterRPCServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MasterRPCServiceIfFactory > handlerFactory_;
};

class MasterRPCServiceMultiface : virtual public MasterRPCServiceIf {
 public:
  MasterRPCServiceMultiface(std::vector<boost::shared_ptr<MasterRPCServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MasterRPCServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MasterRPCServiceIf> > ifaces_;
  MasterRPCServiceMultiface() {}
  void add(boost::shared_ptr<MasterRPCServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void RequestWorker(WorkerMeta& _return, const int32_t client_pid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RequestWorker(_return, client_pid);
    }
    ifaces_[i]->RequestWorker(_return, client_pid);
    return;
  }

  void GetCurrentClientStates(std::vector<MasterClientMetaState> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetCurrentClientStates(_return);
    }
    ifaces_[i]->GetCurrentClientStates(_return);
    return;
  }

};



#endif
